-- Modelo de avión que más distancia ha recorrido

CREATE VIEW DISTANCIA_AVION AS
(SELECT AVION,sum(DISTANCIA) AS DISTANCIA
FROM VUELO
GROUP BY AVION)
UNION ALL
(SELECT AVION, sum(DISTANCIA_ADICCIONAL) AS DISTANCIA
FROM ESCALAS_EMERGENCIAS
GROUP BY AVION);

