CREATE VIEW peliculas_saga AS
(
  SELECT PRECUELA AS PELICULAS_SAGA
  FROM ES_PRECUELA
  INNER JOIN PELICULA ON PRECUELA = PELICULA.ID AND PELICULA.TITULO = 'Fast and furious'
)
UNION (
  SELECT SECUELA AS PELICULAS_SAGA
  FROM ES_SECUELA
  INNER JOIN PELICULA ON SECUELA = PELICULA.ID AND PELICULA.TITULO = 'Fast and furious'
);

CREATE VIEW actores_saga AS
SELECT PERSONA
FROM ACTOR_PELICULA
WHERE PELICULA IN( SELECT *
                   FROM peliculas_saga);

SELECT PERSONA
FROM actores_saga
GROUP BY PERSONA
HAVING count(*) >= ((SELECT count(*)
                  FROM peliculas_saga) / 2);