CREATE OR REPLACE VIEW MAX_EMP_TEMP_OPTIM AS
  SELECT TEMPORADA, MAX(NUM) AS max FROM EMPATES GROUP BY TEMPORADA;
SELECT * FROM empates
    INNER JOIN MAX_EMP_TEMP_OPTIM
    ON empates.TEMPORADA = MAX_EMP_TEMP_OPTIM.TEMPORADA
  WHERE
    EMPATES.NUM = MAX_EMP_TEMP_OPTIM.max;

CREATE OR REPLACE VIEW EQUIPO_MAX_EMPATES_OPTIM AS
  SELECT
    EMPATES.TEMPORADA,
    EMPATES.NUM,
    EMPATES.EQUIPO
  FROM empates
    INNER JOIN MAX_EMP_TEMP_OPTIM
    ON empates.TEMPORADA = MAX_EMP_TEMP_OPTIM.TEMPORADA
  WHERE
    EMPATES.NUM = MAX_EMP_TEMP_OPTIM.max;


SELECT
  TEMPORADA.ANYO,
  TEMPORADA.DIVISION,
  EQUIPO,
  NUM
FROM EQUIPO_MAX_EMPATES_OPTIM
  INNER JOIN TEMPORADA ON TEMPORADA = TEMPORADA.ID;